---
apiVersion: v1
kind: Service
metadata:
  name: horcrux-svc
spec:
  type: ClusterIP
  selector:
    app: horcrux
  ports:
    - protocol: TCP
      name: horcrux
      port: 2222
      targetPort: 2222
