---
apiVersion: v1
kind: Service
metadata:
  name: gaia-full-node-svc
spec:
  type: ClusterIP
  selector:
    app: gaia
  ports:
    - protocol: TCP
      name: gaia-node
      port: 26657
      targetPort: 26657
    - protocol: TCP
      name: horcrux
      port: 1234
      targetPort: 1234
