apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-manager-api
  namespace: gaia
  labels:
    app: secret-manager-api
spec:
  selector:
    matchLabels:
      app: secret-manager-api
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-manager-api
    spec:
      serviceAccountName: secret-ksa
      containers:
        - name: secret-manager-api
          image: jeremymc99/gaia:gke-secret-manager-1.0
          ports:
            - name: get-password
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROJECT_ID
              value: "gaia-node-on-kube"
            - name: SECRET_NAME
              value: "my-pkey-password"
            - name: SECRET_VERSION
              value: "1"
