---
apiVersion: v1
kind: Service
metadata:
  name: secret-manager-api-svc
spec:
  type: ClusterIP
  selector:
    app: secret-manager-api
  ports:
    - protocol: TCP
      name: get-password
      port: 8080
      targetPort: 8080
